"""Create user and role tables 

Revision ID: 0d829cc50030
Revises: 6aaa7a9de60d
Create Date: 2026-08-11 16:29:03.818783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d829cc50030'
down_revision: Union[str, Sequence[str], None] = '6aaa7a9de60d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('status', sa.Integer(), nullable=False))
    op.add_column('userdata', sa.Column('status', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userdata', 'status')
    op.drop_column('roles', 'status')
    # ### end Alembic commands ###
